syntax = "proto3";

import "PortfolioConfiguration/Models/Responses/portfolio_responses.proto";

package cryptic.portfolio_configuration.models.requests;

message CreatePortfolioRequest {
  string name = 1;
  int32 owner_id = 2;
  int64 created_at = 3;
}

message GetPortfolioRequest {
  int32 id = 1;
  int32 owner_id = 2;
}

message GetPortfoliosByOwnerRequest {
  int32 owner_id = 1;
}

message UpdatePortfolioRequest {
  models.responses.Portfolio portfolio = 1;
}

message DeletePortfolioRequest {
  int32 id = 1;
  int32 owner_id = 2;
}