name: CI/CD Deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ConnString: ${{ secrets.ConnString }}
      Schema: ${{ secrets.Schema }}

    steps:
      # 1. Чекаут коду
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      # 2. Налаштовуємо QEMU для емуляції ARM64
      - name: Set up QEMU (for cross-building)
        uses: docker/setup-qemu-action@v2

      # 3. Налаштовуємо Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 4. Логін до Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Збираємо й пушимо мультиархітектурний образ (amd64 + arm64)
      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/cryptic-portfolio_configuration-service:latest

      # 6. Деплой через SSH (ваша звичайна логіка)
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 20.215.241.137
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: 22
          script: |
            # Підтягуємо оновлений образ
            docker pull ${{ secrets.DOCKER_USERNAME }}/cryptic-portfolio_configuration-service:latest

            # Остановлюємо, видаляємо старий контейнер
            docker stop cryptic-portfolio_configuration-service || true
            docker rm cryptic-portfolio_configuration-service || true

            # Запускаємо новий контейнер
            docker run -d --name cryptic-portfolio_configuration-service -p 5001:5001 \
              -e "ConnString=${{ secrets.ConnString }}" \
              -e "Schema=${{ secrets.Schema }}" \
              -e "BlockchainInteractionConnString=${{ secrets.BLOCKCHAININTERACTIONCONNSTRING }}" \
              -e "AnalyticConnString=${{ secrets.ANALYTICCONNSTRING }}" \
              ${{ secrets.DOCKER_USERNAME }}/cryptic-portfolio_configuration-service:latest
